apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  OPENAI_API_KEY: "Base64-encoded-API-KEY"
  AZURE_SERVICE_BUS_CONNECTION_STRING: "RW5kcG9pbnQ9c2I6Ly9hbGdvbnF1aW5wZXRzdG9yZS5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PVlIa0J0YWkvcmRuOVJxaUlRemNCb29KZTFLR3ZyY0RuRStBU2JQbCtUbEU9"
  ORDER_QUEUE_NAME: "b3JkZXItcXVldWU="
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

